import type { BranchCatalog } from '../types';
import { ADMINISTRATIVO_CATALOG } from './administrativo';
import { CONSTITUCIONAL_CATALOG } from './constitucional';
import { CIVIL_CATALOG } from './civil';
import { LABORAL_CATALOG } from './laboral';
import { FAMILIA_CATALOG } from './familia';
import { PENAL_CATALOG } from './penal';
import { SOCIETARIO_CATALOG } from './societario';
import { TRIBUTARIO_CATALOG } from './tributario';
import { TRANSITO_CATALOG } from './transito';
import { NOTARIAL_CATALOG } from './notarial';
import { CONTRATACION_CATALOG } from './contratacion';
import { INTERNACIONAL_CATALOG } from './internacional';
import { SUPERINTENDENCIAS_CATALOG } from './superintendencias';

/**
 * Every branch catalogue the product ships with.
 *
 * Generated by `python backend/scripts/build-catalog.py`. Adding a branch means
 * adding one entry to that script's BRANCHES list — nothing else in the module
 * changes, so the service never has to learn a branch name to load it.
 */
export const ALL_CATALOGS: BranchCatalog[] = [
  ADMINISTRATIVO_CATALOG,
  CONSTITUCIONAL_CATALOG,
  CIVIL_CATALOG,
  LABORAL_CATALOG,
  FAMILIA_CATALOG,
  PENAL_CATALOG,
  SOCIETARIO_CATALOG,
  TRIBUTARIO_CATALOG,
  TRANSITO_CATALOG,
  NOTARIAL_CATALOG,
  CONTRATACION_CATALOG,
  INTERNACIONAL_CATALOG,
  SUPERINTENDENCIAS_CATALOG
];
