import type { BranchCatalog } from '../types';
import { ADMINISTRATIVO_CATALOG } from './administrativo';
import { CONSTITUCIONAL_CATALOG } from './constitucional';
import { CIVIL_CATALOG } from './civil';
import { LABORAL_CATALOG } from './laboral';
import { FAMILIA_CATALOG } from './familia';

/**
 * Every branch catalogue the product ships with.
 *
 * Generated by `python backend/scripts/build-catalog.py`. Adding a branch means
 * adding one entry to that script's BRANCHES list — nothing else in the module
 * changes, so the service never has to learn a branch name to load it.
 */
export const ALL_CATALOGS: BranchCatalog[] = [
  ADMINISTRATIVO_CATALOG,
  CONSTITUCIONAL_CATALOG,
  CIVIL_CATALOG,
  LABORAL_CATALOG,
  FAMILIA_CATALOG
];
